version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/jsdom"
    versions:
    - 16.2.6
    - 16.2.7
    - 16.2.9
  - dependency-name: jest
    versions:
    - 24.9.0
    - 26.6.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: tslint
    versions:
    - 6.1.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: ts-jest
    versions:
    - 24.3.0
