language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm test
  - npm run coverage
  - npm i -g codecov
after_success:
  - codecov
deploy:
  skip_cleanup: true
  on:
    tags: true
  provider: npm
  email: d@dashdashzako.net
  api_key:
    secure: c4QxNky3XoWuDrne/k7NnvWrvG9KVVFlQ8d2CDPiRK66qs2QgCyNyjDUTrHgN6Ry3gMS6mavyxSQmVFaVcZpjjwej9u8C+cuSZpkAufBfka8joNnIHVI+niVaJNGef8sT3GGpwasj0JQ04PJgeQkXfXRu//QSlGUmdiW/6NpM9PmVsjPEj0uLVYyYKYLqy7RBg9zN8GordfB1UsEadsf/icdkiTrXSbWKWIvGUMaUc5WbDrQ1dE6CkRoPTVAUzDnsSOVQiHYQpP7Acvj4dNc2y7DY9Efky1PW5/tcondprz6Bl6Hy8GOqITXi/G4N4aYpOmCMif0pohLpyU/4i/BnP7qcJM7uXG+VYwMdJqMr0C26L7SDL4Dmu5hfq9MBP8mziGJaqazswYy6sDLWWKkSfn5/6FjDv70Cnw177/9ISgUlCQXDkkh/LA5/i7Vi6GQDlvUaKMmxz3Y7rWR/4HynnHcZFbCjfutXa9/mrYTra+VGKJOPVQVD1z8Pkp05wUO7VOXA7ULBesvHHOBKYiet4ylO7H+64lAh12P8QQRkvW0nNtxgbfo5z+sVGzxU3yqRXmgYvBZt25GzAlKDpUR8ZmJIERPzksy7YiXGoNCTyvF1BgZqiluu6OgduH4+T7MEMwGw5JrLPhvJ8BgIdAfV4ov4dz/uNqvMpEaiXToTLQ=
